### ISSUE TITLE
[FEATURE] Login and sign up

### ISSUE THREAD

**Issue by Kuldeepsinghrajpoot** [ajaynegi45/Uttarakhand-Culture-NewUI#100]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

here we have to make a signup and login pages

### Feature Description

When the user logs into the dashboard, they can book a cab or bike to visit temples and other popular places

### Would you like to work on this feature?

Yes

### Implementation Plan

Create the login and sign-up pages using react-form-hooks and Shadcn for a seamless experience.

**Comment by Prabal-verma** [comment]
hey @Kuldeepsinghrajpoot you can start working on the feature

**Comment by ajaynegi45** [comment]
Duplicate https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/34
