### ISSUE TITLE
[FEATURE] Testimonials feature to your project

### ISSUE THREAD

**Issue by goli17** [ajaynegi45/Uttarakhand-Culture-NewUI#101]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Currently, there is no section on the website to showcase user testimonials or feedback. Adding this feature would enhance user engagement and provide social proof for potential users

### Feature Description

Implement a Testimonials section where users can view feedback and experiences from others who have engaged with the Uttarakhand Culture project. This feature can help build trust and credibility among visitors.

### Screenshots

[
<img width="1680" alt="Screenshot 2024-10-07 at 1 50 52 PM" src="https://github.com/user-attachments/assets/6ba90230-47bf-4e1a-a46e-6ebb8ff536d6">
](url)

### Would you like to work on this feature?

Yes

### Implementation Plan

1. Create Testimonials Component: Develop a new component, Testimonials.tsx, to display user feedback in a visually appealing format (card or carousel layout).

2. Data Structure: Define a structure for storing testimonials, which may include:

- User's name
- User's role or affiliation
- User feedback
- User's image

3. Static Data: Start with a set of static testimonials to demonstrate functionality.
4. Integration: Add the Testimonials component to the appropriate layout or home page to make it visible to users.

**Comment by ajaynegi45** [comment]
duplicate https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/37
