### ISSUE TITLE
[FEATURE]  I will add logos for GitHub and other social media at the footer 

### ISSUE THREAD

**Issue by lakshmirajvagu** [ajaynegi45/Uttarakhand-Culture-NewUI#108]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

There is no logos at the footer for social media I will add if possible I will add Instagram link too

### Feature Description

I will add logos to the footer by using html and css

### Screenshots

![Screenshot_2024-10-08-18-33-43-48_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/5b9b8e5b-65b6-4ac2-9902-e17b15b45004)

### Would you like to work on this feature?

Yes

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
can i work on it
