### ISSUE TITLE
[BUG] In place of static text for social media i would like to add social media icons here for better user experience

### ISSUE THREAD

**Issue by tarunkumar2005** [ajaynegi45/Uttarakhand-Culture-NewUI#109]
### Is this a new issue?

- [X] I have searched "open" and "closed" issues, and this is not a duplicate.

### Bug Description

In place of static text for social media i would like to add social media icons here for better user experience

### Screenshots

![image](https://github.com/user-attachments/assets/02675606-df24-4424-9447-82723840681c)

### Would you like to work on this issue?

Yes

### Implementation Plan

@ajaynegi45 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by ajaynegi45** [comment]
no need
