### ISSUE TITLE
[Create Nature Page ] I can recreate the Nature page of website

### ISSUE THREAD

**Issue by dev129** [ajaynegi45/Uttarakhand-Culture-NewUI#115]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Nature is something UK is famous for and adding a nature section will surely help out. 

### Feature Description

Keeping the Figma design in mind, i would like to design the Nature Page

### Would you like to work on this feature?

Yes

### Implementation Plan

Firstly, I would study the Figma Design, construct a wireframe and then start working on the design, the pics can be taken from the Figma design

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> Nature is something UK is famous for and adding a nature section will surely help out.
> 
> ### Feature Description
> Keeping the Figma design in mind, i would like to design the Nature Page
> 
> ### Screenshots
> _No response_
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> Firstly, I would study the Figma Design, construct a wireframe and then start working on the design, the pics can be taken from the Figma design

Hi @dev129,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Before making any contributions, please read the Readme.md file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the Contributing.md file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by dev129** [comment]
https://github.com/user-attachments/assets/3dedc64f-328f-42bc-beae-34801ed5f19f

Iahve recreated the page @ajaynegi45 , I am waiting for your PR approval.

**Comment by dev129** [comment]
Hello @ajaynegi45 are you still interested or not ?

**Comment by dev129** [comment]
@ajaynegi45 , are you interested or shall I close the request ?

**Comment by dev129** [comment]
@ajaynegi45 , if you are not interested , tell me your reply, this is not fair.

**Comment by ajaynegi45** [comment]
> @ajaynegi45 , if you are not interested , tell me your reply, this is not fair.

I didn't get any notification of your message

**Comment by ajaynegi45** [comment]
> bandicam.2024-10-16.10-32-45-804.mp4 
> Iahve recreated the page @ajaynegi45 , I am waiting for your PR approval.

This design is good. Make responsive and Improve Images.

**Comment by dev129** [comment]
@ajaynegi45, I tagged you 4 times , you seriously did not notice ? Also the page is responsive, the only thing neede was what were your thought on the design.

**Comment by ajaynegi45** [comment]
> @ajaynegi45, I tagged you 4 times , you seriously did not notice ? Also the page is responsive, the only thing neede was what were your thought on the design.

I didn't get any notification from github regarding your message. If I didn't reply in 24hr then ping me on linkedin

**Comment by ajaynegi45** [comment]
> @ajaynegi45, I tagged you 4 times , you seriously did not notice ? Also the page is responsive, the only thing neede was what were your thought on the design.

Make pr with the design, then I will check the design
