### ISSUE TITLE
[FEATURE] Adding password hide show button

### ISSUE THREAD

**Issue by Sourabh782** [ajaynegi45/Uttarakhand-Culture-NewUI#119]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Currently in login signup page we cant see password that we entered

### Feature Description

I wanted to add toggle button so that we can see password

### Screenshots

![image](https://github.com/user-attachments/assets/2f366ec4-1ddf-4b78-a36a-2ee11eb84723)

![image](https://github.com/user-attachments/assets/a2d3fd9e-a31e-468b-9c0e-a6785919a0a5)

### Would you like to work on this feature?

Yes

### Implementation Plan

i wll add a toggle button in password field to hide or show password

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> Currently in login signup page we cant see password that we entered
> 
> ### Feature Description
> I wanted to add toggle button so that we can see password
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/103349890/375266554-2f366ec4-1ddf-4b78-a36a-2ee11eb84723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Nzg4NzEsIm5iZiI6MTcyODk3ODU3MSwicGF0aCI6Ii8xMDMzNDk4OTAvMzc1MjY2NTU0LTJmMzY2ZWM0LTFkZGYtNGI3OC1hMzZhLTJlZTExZWI4NDcyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwNzQ5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmE4ZjRkZWNkNmM4YTMyYzliOWY1NTA5MWM2NTc1NmU2NDVkMjAxYjMzNmRkZmM4NmJmNDE1ZGY5MDc0ODIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IYuxHwwq4hXxqyZGcXkREQ2zojkSfdsei9D219n3-So)
> 
> ![image](https://private-user-images.githubusercontent.com/103349890/375266947-a2d3fd9e-a31e-468b-9c0e-a6785919a0a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Nzg4NzEsIm5iZiI6MTcyODk3ODU3MSwicGF0aCI6Ii8xMDMzNDk4OTAvMzc1MjY2OTQ3LWEyZDNmZDllLWEzMWUtNDY4Yi05YzBlLWE2Nzg1OTE5YTBhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwNzQ5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTMyNDQwNmFiYjVkOTBlMmZmZTM4Y2ZkZTJmM2RiODc1ZWY2ZGY2NTU2MmZmNDBhM2EyZjdkZjIyMjQzMTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.our95qmWbanpZejthTqEhgIN_NQLJs0aPTFxpdUl_lE)
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> i wll add a toggle button in password field to hide or show password

you can start working
