### ISSUE TITLE
[BUG] Password preset bug

### ISSUE THREAD

**Issue by Sourabh782** [ajaynegi45/Uttarakhand-Culture-NewUI#120]
### Is this a new issue?

- [X] I have searched "open" and "closed" issues, and this is not a duplicate.

### Bug Description

The paddword fields of login and signin page are interlinked

### Steps to Reproduce

go to login page
type password
switch to signin page

### Screenshots

https://github.com/user-attachments/assets/dfefd6c8-2b97-46e7-a913-f4c46a353910

### Would you like to work on this issue?

Yes

### Implementation Plan

properly handling fields

**Comment by ajaynegi45** [comment]
> ### Is this a new issue?
> * [x]  I have searched "open" and "closed" issues, and this is not a duplicate.
> 
> ### Bug Description
> The paddword fields of login and signin page are interlinked
> 
> ### Steps to Reproduce
> go to login page type password switch to signin page
> 
> ### Screenshots
>  Uttarakhand.Culture.-.Explore.Devbhoomi.s.Heritage.Traditions.and.Natural.Beauty.-.Google.Chrome.2024-10-10.12-48-13.mp4 
> ### Would you like to work on this issue?
> Yes
> 
> ### Implementation Plan
> properly handling fields

Hi @Sourabh782,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Before making any contributions, please read the [Readme.md](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/README.md) file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the [Contributing.md](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/contributing.md) file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by Sourabh782** [comment]
Thanks @ajaynegi45 working on it

**Comment by Sourabh782** [comment]
hii @ajaynegi45, can you provide .env eg?
