### ISSUE TITLE
[FEATURE] Testimonials

### ISSUE THREAD

**Issue by komal-agarwal5** [ajaynegi45/Uttarakhand-Culture-NewUI#121]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

I wat to design a Testimonials page 

### Feature Description

in the figma file a section for testimonials has been designed i want to create thatand add dummy reviews for now to enhance overall effect.

### Screenshots

![image](https://github.com/user-attachments/assets/dfcb815a-44d7-4a39-a2a1-6c5cd35736ab)

### Would you like to work on this feature?

Yes

### Implementation Plan

I want to work on this for Hacktoberfest'24

**Comment by komal-agarwal5** [comment]
@ajaynegi45 The waiting label is still there so should I start or wait?

**Comment by ajaynegi45** [comment]
Hi @komal-agarwal5,

Hope you're doing great! 😊 Just wanted to check in and see how things are coming along with the issue you're working on. Any progress or updates you’d like to share? And if you’ve run into any roadblocks or need a hand with anything, please don’t hesitate to reach out!

Looking forward to hearing from you!

**Comment by komal-agarwal5** [comment]
I won't be able to continue with this.

**Comment by ajaynegi45** [comment]
> I won't be able to continue with this.

why ?
