### ISSUE TITLE
Contact Us" Button of home page is Not Redirecting to Contact Page

### ISSUE THREAD

**Issue by simmi-verma** [ajaynegi45/Uttarakhand-Culture-NewUI#136]
### Bug Description

The "Contact Us" button on our website is currently not functioning as intended. Clicking the button does not redirect users to the "Contact Us" page, which hinders communication and support requests.

I  would you like to work on this issue .Please assign to me

**Comment by officeneerajsaini** [comment]
@ajaynegi45  please mention why you closed this issue .
