### ISSUE TITLE
[FEATURE] Interactive Map for Cultural Hotspots

### ISSUE THREAD

**Issue by ajaynegi45** [ajaynegi45/Uttarakhand-Culture-NewUI#149]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Feature Description

Develop an interactive map to highlight Uttarakhand's cultural hotspots, historical places, and famous temples. The map should be similar in functionality to the one on [Uttarakhand Tourism](https://uttarakhandtourism.gov.in), but with enhanced features. It should display only the Uttarakhand region and provide the following functionalities:

1. **Clickable Markers with Descriptions:** Each location will have a marker with descriptions that provide relevant information about cultural significance, history, or location.
  
2. **District-Wise Zoom:** The map will initially display all the districts of Uttarakhand with pins or markers. When a user clicks on a district, the map will zoom in to show cultural hotspots, temples, and historical places specific to that district.

3. **Modern UI:** Design the map to have a sleek and user-friendly interface, similar to the one on [website](https://bento.me/codiescoder). This modern aesthetic will enhance the overall user experience.

4. **Lightweight & Responsive:** Ensure the map is lightweight, loads quickly, and is smoothly usable on older mobile devices.

**Additional Notes:**
- Ensure the map is limited to only Uttarakhand's geographical region.
- The user should be able to zoom into districts for detailed exploration.
- Prioritize smooth performance for mobile users.

**References:**
- [Uttarakhand Tourism Map](https://uttarakhandtourism.gov.in)
- [Uttarakhand Culture](https://uttarakhand-culture.vercel.app/map)
- [SVG MAP](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/public/mapUk.svg)
- [Other Resource](https://ajaynegi.notion.site/Resources-f92bcb910d0544a1a8db50cc3ef79cfe)

Before making any contributions, please read the [Readme.md](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/README.md) file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the [Contributing.md](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/contributing.md) file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

**Comment by vashujoshi** [comment]
@ajaynegi45 i can do this leave it to me . 
FOR some reason i am feeling motivated to work on this as its my state.#UK01

**Comment by ajaynegi45** [comment]
> @ajaynegi45 i can do this leave it to me .
> 
> FOR some reason i am feeling motivated to work on this as its my state.#UK01



Hi @vashujoshi,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Before making any contributions, please read the Readme.md file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the Contributing.md file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by ajaynegi45** [comment]
Hi @vashujoshi,

Hope you're doing great! 😊 Just wanted to check in and see how things are coming along with the issue you're working on. Any progress or updates you’d like to share? And if you’ve run into any roadblocks or need a hand with anything, please don’t hesitate to reach out!

Looking forward to hearing from you!

**Comment by vashujoshi** [comment]
@ajaynegi45 sorry busy with some ongoing project and hackathon
would like you to assign these issues to someone else so they can work on it. sorry for not continuing
