### ISSUE TITLE
[FEATURE]:To add dark and light mode toggle 

### ISSUE THREAD

**Issue by sv410** [ajaynegi45/Uttarakhand-Culture-NewUI#152]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

to add dark and light toggle for view comfort of viewing!

### Feature Description

dark and light mode toggle 

### Screenshots

![WhatsApp Image 2024-10-15 at 12 05 39 PM](https://github.com/user-attachments/assets/150c9f2f-7e5e-4a78-b53f-6750da92f6ce)
![WhatsApp Image 2024-10-15 at 12 06 01 PM](https://github.com/user-attachments/assets/c96b0786-fc6a-4980-9998-f6891902ebb4)

### Would you like to work on this feature?

Yes

### Implementation Plan

i want to work on this issue and by using the html , css and js1

**Comment by Prabal-verma** [comment]
@ajaynegi45 have a look at this

**Comment by sv410** [comment]
@Prabal-verma can u pls assign me

**Comment by Prabal-verma** [comment]
duplicate issue #102
