### ISSUE TITLE
Implement "View Location" Modal with Map on Trekking Page

### ISSUE THREAD

**Issue by IkkiOcean** [ajaynegi45/Uttarakhand-Culture-NewUI#169]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Currently, there is no functionality on the trekking page that allows users to view the specific geographic locations of trekking spots. This missing feature limits the user's ability to visualize the treks and plan their trips accordingly. Adding a map modal will enhance the user experience by providing crucial location information.

### Feature Description

Implement a "View Location" modal on the trekking page that displays a map for each trekking location. The modal will open upon clicking a "View Location" button on the trekking card, showing the exact location of the trek. The map will be interactive, allowing users to zoom in, zoom out, and pan to explore the surrounding area.

### Would you like to work on this feature?

Yes

### Implementation Plan

I can use leaflet js to implement it or any other map api which you would recommend

**Comment by ajaynegi45** [comment]
> This missing feature limits the user's ability to visualize the treks and plan their trips accordingly. Adding a map modal will enhance the user experience by providing crucial location information.

Hi @IkkiOcean,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Before making any contributions, please read the Readme .md file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the Contributing .md file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.
