### ISSUE TITLE
[BUG] Brief description

### ISSUE THREAD

**Issue by viveksarkar0** [ajaynegi45/Uttarakhand-Culture-NewUI#176]
### Is this a new issue?

- [X] I have searched "open" and "closed" issues, and this is not a duplicate.

### Bug Description

i go to the login page the ui not look good please let me fix this design for you like registreation page 

this not loook got let me fix this 

### Steps to Reproduce

go to signup page 
and login page

### Screenshots

<img width="1470" alt="Screenshot 2024-10-19 at 1 48 39 PM" src="https://github.com/user-attachments/assets/dd018679-dd52-4519-8621-051cc21b1995">

### Would you like to work on this issue?

Yes

**Comment by ajaynegi45** [comment]
> i go to the login page the ui not look good please let me fix this design for you like registreation page

Hi @viveksarkar0,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Before making any contributions, please read the Readme.md file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the Contributing.md file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by viveksarkar0** [comment]
Ok @ajaynegi45 I'm starting by today

**Comment by viveksarkar0** [comment]
sir it not assigned yet

**Comment by ajaynegi45** [comment]
Hi @viveksarkar0,

Hope you're doing great! 😊 Just wanted to check in and see how things are coming along with the issue you're working on. Any progress or updates you’d like to share? And if you’ve run into any roadblocks or need a hand with anything, please don’t hesitate to reach out!

Looking forward to hearing from you!

**Comment by viveksarkar0** [comment]
Yes completed it for  some college work it got late I will pull by 6 to 7 currently I am in college

**Comment by ajaynegi45** [comment]
> Yes completed it for some college work it got late I will pull by 6 to 7 currently I am in colleg

Okay
