### ISSUE TITLE
[FEATURE]:Implement Offline Detection Feature for Better User Interaction And Traffic 

### ISSUE THREAD

**Issue by laxmanp090404** [ajaynegi45/Uttarakhand-Culture-NewUI#186]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

The problem arises when users lose internet connectivity while browsing the Uttarkhand-Culture website. Currently, there is no indication that they are offline, which can cause confusion as the content may not load or update. This results in a poor user experience as they might assume the website is broken or slow, when in reality it's a connectivity issue.

### Feature Description

I would like to implement a feature that detects when a user goes offline using a custom React hook (`window.navigator.onLine`). This feature would display a dedicated "You are offline" page, notifying the user about their network status. The custom hook will listen for the `online` and `offline` events and update the app accordingly. The user will be redirected to the offline page whenever they lose connectivity, providing a clear message and a prompt to refresh the page once they regain internet access.
**Screenshots**  
Since this feature hasn’t been implemented yet, here’s a mock-up of how the offline page could look:

1. A centered message that says, "You are currently offline. Please check your connection."
2. A retry or refresh button to reload the page when the user reconnects.

### Similar to below:
![image](https://github.com/user-attachments/assets/45cf1a3f-d8c9-49ff-bacb-8cd954aa5e6f)

**Screenshots/Video of Feature**  
Once the feature is implemented, we can share a video showcasing the transition between online and offline states, highlighting the seamless user experience when the page detects connectivity issues.

### Screenshots

PROBLEM:
![image](https://github.com/user-attachments/assets/f5dc6c68-fb2f-4808-abed-d9af66b9d173)

FEATURE DEMO:
![image](https://github.com/user-attachments/assets/45cf1a3f-d8c9-49ff-bacb-8cd954aa5e6f)

### Would you like to work on this feature?

Yes

**Comment by laxmanp090404** [comment]
@ajaynegi45  Please into the issue and assign me.
Thank you.

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> The problem arises when users lose internet connectivity while browsing the Uttarkhand-Culture website. Currently, there is no indication that they are offline, which can cause confusion as the content may not load or update. This results in a poor user experience as they might assume the website is broken or slow, when in reality it's a connectivity issue.
> 
> ### Feature Description
> I would like to implement a feature that detects when a user goes offline using a custom React hook (`window.navigator.onLine`). This feature would display a dedicated "You are offline" page, notifying the user about their network status. The custom hook will listen for the `online` and `offline` events and update the app accordingly. The user will be redirected to the offline page whenever they lose connectivity, providing a clear message and a prompt to refresh the page once they regain internet access. **Screenshots** Since this feature hasn’t been implemented yet, here’s a mock-up of how the offline page could look:
> 
> 1. A centered message that says, "You are currently offline. Please check your connection."
> 2. A retry or refresh button to reload the page when the user reconnects.
> 
> ### Similar to below:
> ![image](https://private-user-images.githubusercontent.com/122375687/374438375-45cf1a3f-d8c9-49ff-bacb-8cd954aa5e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTkyNzgsIm5iZiI6MTcyOTU5ODk3OCwicGF0aCI6Ii8xMjIzNzU2ODcvMzc0NDM4Mzc1LTQ1Y2YxYTNmLWQ4YzktNDlmZi1iYWNiLThjZDk1NGFhNWU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMjA5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjQ5ZDY4YWZlYzQ5MjAwZWFiMTg4YzUzODUwMWRlOWM4NmZhNWI2OGY4YjI1MmZlMTQ0ZjYwNTI0OTQ5OGRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DA-3wELKA_3YXRl8mCFVCtVAEdxS_U0IuU0bxR27y9g)
> 
> **Screenshots/Video of Feature** Once the feature is implemented, we can share a video showcasing the transition between online and offline states, highlighting the seamless user experience when the page detects connectivity issues.
> 
> ### Screenshots
> PROBLEM: ![image](https://private-user-images.githubusercontent.com/122375687/378298271-f5dc6c68-fb2f-4808-abed-d9af66b9d173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTkyNzgsIm5iZiI6MTcyOTU5ODk3OCwicGF0aCI6Ii8xMjIzNzU2ODcvMzc4Mjk4MjcxLWY1ZGM2YzY4LWZiMmYtNDgwOC1hYmVkLWQ5YWY2NmI5ZDE3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMjA5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTA1YzRkZmRiZTEzNzA5Y2Y5YWQ2ZjAzMDUwMzllODdjNjc1YTYzMTk3OGIzMzMyNjkyMzMzNGJhNmMxMjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A3UfPnEnmfm17j5Dnffb8gfJGZp7-WBqFQ1CsIpmF1Y)
> 
> FEATURE DEMO: ![image](https://private-user-images.githubusercontent.com/122375687/374438375-45cf1a3f-d8c9-49ff-bacb-8cd954aa5e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTkyNzgsIm5iZiI6MTcyOTU5ODk3OCwicGF0aCI6Ii8xMjIzNzU2ODcvMzc0NDM4Mzc1LTQ1Y2YxYTNmLWQ4YzktNDlmZi1iYWNiLThjZDk1NGFhNWU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMjA5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjQ5ZDY4YWZlYzQ5MjAwZWFiMTg4YzUzODUwMWRlOWM4NmZhNWI2OGY4YjI1MmZlMTQ0ZjYwNTI0OTQ5OGRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DA-3wELKA_3YXRl8mCFVCtVAEdxS_U0IuU0bxR27y9g)
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> _No response_

No need
