### ISSUE TITLE
[FEATURE] add hacktoberfest and gssoc banner to the readme file

### ISSUE THREAD

**Issue by agarwalbhargavi** [ajaynegi45/Uttarakhand-Culture-NewUI#192]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

i would like to add hacktoberfest and gssoc banner to the readme file.
@ajaynegi45 kindly assign me this issue

### Feature Description

hacktoberfest and gssoc bnaner

### Would you like to work on this feature?

Yes

**Comment by amiya-cyber** [comment]
Hello @agarwalbhargavi i want to work on this can you assign me and add all the labels 
Gssoc
Hacktoberfest 
Level 2 or level 3
