### ISSUE TITLE
ADD a dedicated page for UPCOMING FESTIVAL | UPCOMING FAIR

### ISSUE THREAD

**Issue by shubhagarwal1** [ajaynegi45/Uttarakhand-Culture-NewUI#196]
This page will show the upcoing festivals and fairs in the form of cards 
<img width="1440" alt="Screenshot 2024-10-25 at 4 08 01 AM" src="https://github.com/user-attachments/assets/50ee00d9-c3f8-4a70-ab03-797e9edd38d6">
Hey @ajaynegi45 please assign me this task, would love to work on the feature

**Comment by ajaynegi45** [comment]
> This page will show the upcoing festivals and fairs in the form of cards <img alt="Screenshot 2024-10-25 at 4 08 01 AM" width="1440" src="https://private-user-images.githubusercontent.com/105449260/379955241-50ee00d9-c3f8-4a70-ab03-797e9edd38d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzA5OTgsIm5iZiI6MTcyOTgzMDY5OCwicGF0aCI6Ii8xMDU0NDkyNjAvMzc5OTU1MjQxLTUwZWUwMGQ5LWMzZjgtNGE3MC1hYjAzLTc5N2U5ZWRkMzhkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwNDMxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjNlZTFlMjcxYmFlYTY4ZGI0ZGRjMmQxZmU4MGU0NjE3YjBlNTgwY2Q2NDA0NjhmODUxYmNlMmVmY2NmNjg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zKTEGDuPJgIIvha8FBfQhYKeMS3yYvNow0P3-oHDcLU"> Hey @ajaynegi45 please assign me this task, would love to work on the feature

No need of it
