### ISSUE TITLE
[FEATURE] Add Fillters for sort the trekking 

### ISSUE THREAD

**Issue by nilesh-fatfatwale** [ajaynegi45/Uttarakhand-Culture-NewUI#207]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

user cant find sort details as page has sorting feature level , district , altitude.

### Feature Description

i want to fix this issue to sort all the trekking details according to location height and levels. 

### Screenshots

![image](https://github.com/user-attachments/assets/1a2eb3ba-94b6-4753-975c-e7060fd366c8)

### Would you like to work on this feature?

Yes

**Comment by ajaynegi45** [comment]
> i want to fix this issue to sort all the trekking details according to location

Hi @nilesh-fatfatwale,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Before making any contributions, please read the Readme.md file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the Contributing.md file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by nilesh-fatfatwale** [comment]
hey can you share me more detail about database connections there is no guide for database connection or no proper information

**Comment by nilesh-fatfatwale** [comment]
i was busy last 3 days and now when i almost finish my code then i realize someone already made an pr request and succesfully merged it. one request to you please make sure this project has only 1 issue and if anybody not make pr then assign to someone another guy who really contribute

**Comment by ajaynegi45** [comment]
> i was busy last 3 days and now when i almost finish my code then i realize someone already made an pr request and succesfully merged it. one request to you please make sure this project has only 1 issue and if anybody not make pr then assign to someone another guy who really contribute

You haven't share any update. and he want to work on it then he done it

**Comment by ajaynegi45** [comment]
> i was busy last 3 days and now when i almost finish my code then i realize someone already made an pr request and succesfully merged it. one request to you please make sure this project has only 1 issue and if anybody not make pr then assign to someone another guy who really contribute

Check around it and If there is any scope of improvement which you can complete
