### ISSUE TITLE
[FEATURE]  show map locating famous places in uttarakhand

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [ajaynegi45/Uttarakhand-Culture-NewUI#216]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

show map locating famous places in uttarakhand

### Feature Description

show map locating famous places in uttarakhand

### Screenshots

like this
<img width="958" alt="map" src="https://github.com/user-attachments/assets/66160d4b-ee1e-4eab-9cd8-0e818a2f2fa4">

### Would you like to work on this feature?

Yes

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> show map locating famous places in uttarakhand
> 
> ### Feature Description
> show map locating famous places in uttarakhand
> 
> ### Screenshots
> like this <img alt="map" width="958" src="https://private-user-images.githubusercontent.com/165504668/380448960-66160d4b-ee1e-4eab-9cd8-0e818a2f2fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDE1NjksIm5iZiI6MTczMDAwMTI2OSwicGF0aCI6Ii8xNjU1MDQ2NjgvMzgwNDQ4OTYwLTY2MTYwZDRiLWVlMWUtNGVhYi05Y2Q4LTBlODE4YTJmMmZhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwMzU0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjI1Yzg0ZWU3YzM1NDNiYmRhZGM4YThttps://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/149ZjY2QwODFkNDU2NDIwMzdmNDVlZTNlNmI4OGRjNjcyY2YwY2Q1Y2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UnbIJaLfelSPVqkw1xRiuFzMxhPDrFuhApxOD8dvqZs">
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> _No response_



Duplicated https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/149
