### ISSUE TITLE
[FEATURE] add a button that directly opens maps 

### ISSUE THREAD

**Issue by AE-Hertz** [ajaynegi45/Uttarakhand-Culture-NewUI#220]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

A journey site should have a map functionality to easily open map and save the list in want to go..

### Feature Description

Currently this feat. Is not available. And i will make button handling mobile and large screen sizes.

### Screenshots

![1000016621](https://github.com/user-attachments/assets/565e834f-d23e-48cf-8755-df8e306001cf)

### Would you like to work on this feature?

Yes

### Implementation Plan

Tiny Button will be in header or stick to the page side by side( point out your preferences if any) and will open Google maps on click.

The current issue related to maps does not have any connection or plan to implement this feat, so this will work as standalone feature (that's why it's not duplication).

Assign me this.

**Comment by ajaynegi45** [comment]
Hi @AE-Hertz,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Before making any contributions, please read the Readme.md file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the Contributing.md file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by AE-Hertz** [comment]
@ajaynegi45 i am done making it, Please review and merge it. Thank you. hope you will like :)
