### ISSUE TITLE
[FEATURE] Add Filtering Option for Trekking Locations

### ISSUE THREAD

**Issue by IkkiOcean** [ajaynegi45/Uttarakhand-Culture-NewUI#221]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

We need to implement a filtering option on the trekking page to enhance user experience. This feature will allow users to filter trekking locations based on various criteria such as difficulty level, district, and altitude 

### Feature Description

- Users can filter trekking locations by:
  - **Difficulty Level**: Easy, Medium, Hard
  - **District**:  The location of Trek
  - **Altitude**:  The height of trek
- The filter options should be clearly visible and accessible on the trekking page.
- The list of trekking locations updates dynamically based on the selected filters.
- Ensure that the filtering works seamlessly with existing features.

### Would you like to work on this feature?

Yes

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> We need to implement a filtering option on the trekking page to enhance user experience. This feature will allow users to filter trekking locations based on various criteria such as difficulty level, district, and altitude
> 
> ### Feature Description
> * Users can filter trekking locations by:
>   
>   * **Difficulty Level**: Easy, Medium, Hard
>   * **District**:  The location of Trek
>   * **Altitude**:  The height of trek
> * The filter options should be clearly visible and accessible on the trekking page.
> * The list of trekking locations updates dynamically based on the selected filters.
> * Ensure that the filtering works seamlessly with existing features.
> 
> ### Screenshots
> _No response_
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> _No response_

Hi @IkkiOcean,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Before making any contributions, please read the Readme.md file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the Contributing.md file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.
