### ISSUE TITLE
[FEATURE] Adding Dockerfile for easy usage/installation of Project in any environment

### ISSUE THREAD

**Issue by mayank-0407** [ajaynegi45/Uttarakhand-Culture-NewUI#236]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Feature Description

We can add a Dockerfile to easily use this project in an isolated container, and run the project with 1 command.

### Would you like to work on this feature?

Yes

**Comment by mayank-0407** [comment]
@ajaynegi45 Can you assign this issue to me?

**Comment by ajaynegi45** [comment]
> @ajaynegi45 Can you assign this issue to me?

As I think there is no need of it for this project
