### ISSUE TITLE
[FEATURE] Implement Home Page Design

### ISSUE THREAD

**Issue by ajaynegi45** [ajaynegi45/Uttarakhand-Culture-NewUI#37]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Feature Description

Implement the design for the home page as per the provided mockups. The page should be fully responsive, ensuring optimal user experience across devices with screen widths ranging from 320px to 1440px.

**Tasks:**
1. Implement the provided home page design.
2. Ensure the design is responsive for screen sizes from 320px (mobile) to 1440px (large screens).
3. Ensure fast load times and minimal layout shifts.
4. Follow best practices for clean and maintainable code.

**Expected Outcome:**
- The home page should look consistent with the design mockups.
- It should function seamlessly across all devices (mobile, tablet, desktop).

**Resources:**
- <a href="https://www.figma.com/design/o82aPjIzHairrkqhem3S1Q/New-UI?node-id=252-38&t=pnd9LeK6OUwhckbh-1" target="_blank">Figma Design</a>
- <a href="https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/tree/main/Design" target="_blank">PDF Design</a>

**Additional Notes:**
- Ensure key sections like the hero, navigation, and footer are optimized for SEO.
- Use modern CSS practices like Flexbox/Grid for layout.

**Comment by manu-hn** [comment]
Hey @ajaynegi45, I plan to use Tailwind CSS for this project and will incorporate component libraries if needed. If this works for you, please assign me the task.

**Comment by ajaynegi45** [comment]
> Hey @ajaynegi45, I plan to use Tailwind CSS for this project and will incorporate component libraries if needed. If this works for you, please assign me the task.

Hey @manu-hn, thanks for your interest! For this project, I’d prefer we stick to pure CSS and avoid any CSS frameworks like Tailwind to keep it lightweight. You can use one component library if necessary, but please run it by me before integrating it. This project could get quite large in the future, and I want to minimize any unnecessary load. Let me know if you’re still interested in working on it, and I’ll assign it to you!

**Comment by nilesh-fatfatwale** [comment]
hey can I work on the faq section as you provide Figma design

**Comment by ajaynegi45** [comment]
> hey can I work on the faq section as you provide Figma design

Hi @nilesh-fatfatwale,

Thank you for expressing your interest in working on the "faq section" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by nilesh-fatfatwale** [comment]
> > hey can I work on the faq section as you provide Figma design
> 
> Hi @nilesh-fatfatwale,
> 
> Thank you for expressing your interest in working on the "faq section" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.
> 
> Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

Hey can you give me data what's question and the description should i add in faq section.

**Comment by nilesh-fatfatwale** [comment]
Hey can I work on this faq ?  you don't give me faq section questions and description

**Comment by ajaynegi45** [comment]
> Hey can I work on this faq ? you don't give me faq section questions and description

I will edit the questions and description later. currently you add data according to your understanding

**Comment by Sonuu20** [comment]
Hey @ajaynegi45 can I work on the contact us form...

**Comment by ajaynegi45** [comment]
> Hey @ajaynegi45 can I work on the contact us form...
Yes, you can

**Comment by nilesh-fatfatwale** [comment]
> > Hey can I work on this faq ? you don't give me faq section questions and description
> 
> I will edit the questions and description later. currently you add data according to your understanding

please cheack my latest updated code
