### ISSUE TITLE
[FEATURE] <brief description>

### ISSUE THREAD

**Issue by Madan2468** [ajaynegi45/Uttarakhand-Culture-NewUI#39]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

the footer section isn't well and good looking.

### Feature Description

I would add these type ui matching your theme with the icons for the footer section 

<img width="1253" alt="Screenshot 2024-09-29 at 11 07 03 PM" src="https://github.com/user-attachments/assets/01b717e8-25c0-4aef-89e2-43087438eb43">

### Would you like to work on this feature?

Yes

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> the footer section isn't well and good looking.
> 
> ### Feature Description
> I would add these type ui matching your theme with the icons for the footer section
> 
> <img alt="Screenshot 2024-09-29 at 11 07 03 PM" width="1253" src="https://private-user-images.githubusercontent.com/114483527/372005842-01b717e8-25c0-4aef-89e2-43087438eb43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTk2NzMsIm5iZiI6MTcyNzY5OTM3MywicGF0aCI6Ii8xMTQ0ODM1MjcvMzcyMDA1ODQyLTAxYjcxN2U4LTI1YzAtNGFlZi04OWUyLTQzMDg3NDM4ZWI0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxMjI5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTgzY2IwNTk5OGRjMmNiMTNlNTM1YThiMjc4OTFjNmFhZWU0ZjAwNDJkMTY3ODRhZmVlYjM1YWMyYjM5NzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rKnJx3Mnv4PTYB3DbRTUmYRxZCgD26WVIX1gdlue-NY">
> ### Screenshots
> _No response_
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> _No response_

Hi @Madan2468,

I believe the current footer design works well, and the design you proposed doesn't quite align with our project's style. If you have something more similar to the current footer or an improved version that fits better, feel free to share it with us. Also, please refer to our <a href="https://www.figma.com/design/o82aPjIzHairrkqhem3S1Q/New-UI?node-id=252-38&t=pnd9LeK6OUwhckbh-1" target="_blank">Figma Design</a>
 for reference.
