### ISSUE TITLE
[FEATURE] Create Custom 404 Page with Current Style and Colour Scheme

### ISSUE THREAD

**Issue by myselfshivams** [ajaynegi45/Uttarakhand-Culture-NewUI#41]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Currently, the website lacks a custom 404 error page, which can lead to a poor user experience when users encounter broken links or unavailable content. We need to design and implement a custom 404 page that aligns with the existing UI style and color scheme of the website.

### Feature Description

A custom 404 error page is essential for enhancing user experience when they encounter broken links or unavailable content on the website. Currently, users may see a generic error page that does not align with our branding, potentially leading to frustration. We need to design and implement a custom 404 page that reflects our website's style, color scheme, and overall branding while providing helpful navigation options for users.

### Would you like to work on this feature?

Yes

### Implementation Plan

Design the layout to include a title, a friendly message indicating that the page was not found, and navigation links back to the homepage or other relevant sections, ensuring it aligns with the current UI style and color scheme. Utilize Next.js's built-in CSS modules or styled components for styling. After development, test the page for functionality, ensuring all links work correctly and the layout is responsive across different devices.

### Labels:
- GSSoC
- Hacktoberfest

@ajaynegi45 Please assign this issue to @myselfshivams.

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> Currently, the website lacks a custom 404 error page, which can lead to a poor user experience when users encounter broken links or unavailable content. We need to design and implement a custom 404 page that aligns with the existing UI style and color scheme of the website.
> 
> ### Feature Description
> A custom 404 error page is essential for enhancing user experience when they encounter broken links or unavailable content on the website. Currently, users may see a generic error page that does not align with our branding, potentially leading to frustration. We need to design and implement a custom 404 page that reflects our website's style, color scheme, and overall branding while providing helpful navigation options for users.
> 
> ### Screenshots
> _No response_
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> Design the layout to include a title, a friendly message indicating that the page was not found, and navigation links back to the homepage or other relevant sections, ensuring it aligns with the current UI style and color scheme. Utilize Next.js's built-in CSS modules or styled components for styling. After development, test the page for functionality, ensuring all links work correctly and the layout is responsive across different devices.
> 
> ### Labels:
> * GSSoC
> * Hacktoberfest
> 
> @ajaynegi45 Please assign this issue to @myselfshivams.

Hi @myselfshivams,

Thank you for expressing your interest in working on the "`Create Custom 404 Page with Current Style and Colour Scheme`" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.
