### ISSUE TITLE
[FEATURE] Add Missing Meta Tags for SEO Enhancement

### ISSUE THREAD

**Issue by myselfshivams** [ajaynegi45/Uttarakhand-Culture-NewUI#42]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). 

### Feature Description

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:

- Title tags
- Description tags
- Keywords tags
- Open Graph tags for social media sharing
- Robots meta tag

### Would you like to work on this feature?

Yes

### Implementation Plan

- Implement the necessary meta tags to enhance SEO.
- Ensure that the title and description tags are relevant and optimized for target keywords.
- Verify that Open Graph tags are correctly set up for better social media sharing.
- Test and validate the added meta tags for correctness and effectiveness.

### Labels:
- GSSoC
- Hacktoberfest

@ajaynegi45 Please assign this issue to me(@myselfshivams).

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> The current project lacks essential meta tags that are crucial for search engine optimization (SEO).
> 
> ### Feature Description
> The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:
> 
> * Title tags
> * Description tags
> * Keywords tags
> * Open Graph tags for social media sharing
> * Robots meta tag
> 
> ### Screenshots
> _No response_
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> * Implement the necessary meta tags to enhance SEO.
> * Ensure that the title and description tags are relevant and optimized for target keywords.
> * Verify that Open Graph tags are correctly set up for better social media sharing.
> * Test and validate the added meta tags for correctness and effectiveness.
> 
> ### Labels:
> * GSSoC
> * Hacktoberfest
> 
> @ajaynegi45 Please assign this issue to me(@myselfshivams).

Hi @myselfshivams,

Thank you for expressing your interest in working on the "`Add Missing Meta Tags for SEO Enhancement`" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Please ensure that you write meta tags for every page in the project, including detailed and relevant keywords. Any additional improvements that enhance the SEO of the website are welcome.

Feel free to start working, and if you have any questions or need assistance during the process, don't hesitate to reach out.
