### ISSUE TITLE
[FEATURE] Interactive map feature

### ISSUE THREAD

**Issue by Adrija05** [ajaynegi45/Uttarakhand-Culture-NewUI#51]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

For a particular place I have problem knowing what are the events of that place so what are the best time to visit that place ,that problem can be overcome by adding interactive calendar feature where each dates of that month will have event names written on it.

### Feature Description

Users can view upcoming events, set reminders, and plan their visits to these occasions, making it easy to stay connected with cultural festivities in real-time. It provides a seamless way to track and participate in Uttarakhand's diverse cultural calendar and know the best time to visit the place.

### Screenshots

![calender feature](https://github.com/user-attachments/assets/822c3b6c-fd62-41b6-9796-b1f921c6ea0f)

### Would you like to work on this feature?

Yes

### Implementation Plan

I plan to start by improving the ui part where the user can suggest any event on the particular date of the calendar and after being accepted the event can be seen by everyone .

**Comment by ajaynegi45** [comment]
> I plan to start by improv

This feature is already present in home page. UPCOMING FESTIVAL and UPCOMING FAIR
