### ISSUE TITLE
[FEATURE] <Add Chatbot feature>

### ISSUE THREAD

**Issue by akshjswl** [ajaynegi45/Uttarakhand-Culture-NewUI#55]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

As today's youth are more inclined to interact with technology. A chatbot feature could provide a more engaging and interactive experience, helping users easily access cultural knowledge.
Assign this feature to me.

### Feature Description

These features aim to create an engaging, educational, and interactive experience for users while preserving and promoting the rich cultural heritage of Uttarakhand.

### Screenshots

![chatbot feature](https://github.com/user-attachments/assets/298ac4ac-930c-42fc-8d78-8ff380a8ba8a)

### Would you like to work on this feature?

Yes

### Implementation Plan

I am planning to implement this feature using botpress.

**Comment by ajaynegi45** [comment]
Already exists https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/19
