### ISSUE TITLE
Footer Not Distinguishable from main page

### ISSUE THREAD

**Issue by anuza08** [ajaynegi45/Uttarakhand-Culture-NewUI#57]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

The main page the footer is not looking distinct.

### Feature Description

The footer is distinctly styled with a darker background color, creating a visual separation from the main content area. This design choice enhances the footer's prominence, making it easily identifiable.
The footer includes essential information, such as copyright notices, links to privacy policies, or contact details. The text is also displayed in a white font to ensure consistency and readability.
Additional spacing (margins) is incorporated above the footer, separating it from the main content and ensuring that it does not blend into the body of the page.

### Screenshots

![{409E8E70-CDD3-4D45-9DC6-11C1821C7CA8}](https://github.com/user-attachments/assets/f32d42b5-f220-407a-a76c-f89d84c2a989)

### Would you like to work on this feature?

Yes

### Implementation Plan

Use background images or textures to add depth and visual interest. Consider subtle animations or hover effects on footer links for improved interactivity.

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> The main page the footer is not looking distinct.
> 
> ### Feature Description
> The footer is distinctly styled with a darker background color, creating a visual separation from the main content area. This design choice enhances the footer's prominence, making it easily identifiable. The footer includes essential information, such as copyright notices, links to privacy policies, or contact details. The text is also displayed in a white font to ensure consistency and readability. Additional spacing (margins) is incorporated above the footer, separating it from the main content and ensuring that it does not blend into the body of the page.
> 
> ### Screenshots
> ![{409E8E70-CDD3-4D45-9DC6-11C1821C7CA8}](https://private-user-images.githubusercontent.com/98256478/373294942-f32d42b5-f220-407a-a76c-f89d84c2a989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjczNDgsIm5iZiI6MTcyNzk2NzA0OCwicGF0aCI6Ii85ODI1NjQ3OC8zNzMyOTQ5NDItZjMyZDQyYjUtZjIyMC00MDdhLWE3NmMtZjg5ZDg0YzJhOTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDE0NTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMmU1MWNhZTRiYmFiMDk3OTViZWQ0NjljN2Q5YWU5OTgyOGY2YjNmMjNjYmY0NjNjNzU5MTIyY2JiMWEyMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KgKo7XnI1K5vcrHXv6DqGQWkSuj52J2ITjG2zUZ2dZQ)
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> Use background images or textures to add depth and visual interest. Consider subtle animations or hover effects on footer links for improved interactivity.

https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/37
