### ISSUE TITLE
[BUG] Improve the readability of the the Home page

### ISSUE THREAD

**Issue by vishnuprasad2004** [ajaynegi45/Uttarakhand-Culture-NewUI#67]
### Is this a new issue?

- [X] I have searched "open" and "closed" issues, and this is not a duplicate.

### Bug Description

The text is gray and small, which can be hard for older people to read. The images are also very small.

We can make the text darker with native words emphasized through (italics/bold), and the images bigger.

### Would you like to work on this issue?

Yes

### Implementation Plan

We can make the text darker with native words emphasized through (italics/bold), and the images bigger.
This would improve the user experience and correctly showcase Uttarakhand's heritage.

**Comment by ajaynegi45** [comment]
> ### Is this a new issue?
> * [x]  I have searched "open" and "closed" issues, and this is not a duplicate.
> 
> ### Bug Description
> The text is gray and small, which can be hard for older people to read. The images are also very small.
> 
> We can make the text darker with native words emphasized through (italics/bold), and the images bigger.
> 
> ### Steps to Reproduce
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Would you like to work on this issue?
> Yes
> 
> ### Implementation Plan
> We can make the text darker with native words emphasized through (italics/bold), and the images bigger. This would improve the user experience and correctly showcase Uttarakhand's heritage.

https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/37
