### ISSUE TITLE
Visiblity issue of text

### ISSUE THREAD

**Issue by Sourabh782** [ajaynegi45/Uttarakhand-Culture-NewUI#68]
### Is this a new issue?

- [X] I have searched "open" and "closed" issues, and this is not a duplicate.

### Bug Description

The text is hardly visible

### Steps to Reproduce

just open the app and see the text is barely visible

### Screenshots

![Screenshot 2024-10-04 201953](https://github.com/user-attachments/assets/262aa003-f409-45e2-b6c5-b5ba02adc4a7)

### Would you like to work on this issue?

Yes

### Implementation Plan

want to chnage font style or add some weight in text

**Comment by ajaynegi45** [comment]
> ### Is this a new issue?
> * [x]  I have searched "open" and "closed" issues, and this is not a duplicate.
> 
> ### Bug Description
> The text is hardly visible
> 
> ### Steps to Reproduce
> just open the app and see the text is barely visible
> 
> ### Screenshots
> ![Screenshot 2024-10-04 201953](https://private-user-images.githubusercontent.com/103349890/373686710-262aa003-f409-45e2-b6c5-b5ba02adc4a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTk2NTgsIm5iZiI6MTcyODA1OTM1OCwicGF0aCI6Ii8xMDMzNDk4OTAvMzczNjg2NzEwLTI2MmFhMDAzLWY0MDktNDVlMi1iNmM1LWI1YmEwMmFkYzRhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNjI5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjU0NzdlYjg2MmYwYmM4MTBiNmEzNTJlOTc3ZjAxMjM2MTAxOGNlYTg2OWNmMzI4OTgxNmY1OTY0N2NhY2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sg59ez7LtiG4dSZrLqX1O6Wb_V5xqkCmA9hY5i5QwKY)
> 
> ### Would you like to work on this issue?
> Yes
> 
> ### Implementation Plan
> want to chnage font style or add some weight in text

Hey @Sourabh782,

Thanks for showing interest in tackling this issue! I'd be happy to assign it to you, but before I do, could you walk me through how you plan to implement this feature in detail?

Also, before jumping in, I recommend giving the [Readme.md](https://github.com/ajaynegi45/LibraryMan-API/blob/main/README.md) a thorough read. It'll help you get a solid grasp of the project's goals and purpose. Plus, check out the [[Contributing.md](https://github.com/ajaynegi45/LibraryMan-API/blob/main/Contributing.md) file for some handy guidelines that’ll make your contribution process smoother, especially if you're new around here.

If you run into any questions or need help along the way, don’t hesitate to reach out!

**Comment by Sourabh782** [comment]
@ajaynegi45 i am planning on changing text colour and font weight og the text items, so that it would be visible better, currently the text font weight is so less that its becoming overwhemed by surrounding white space

**Comment by ajaynegi45** [comment]
start working

**Comment by Sourabh782** [comment]
Sure @ajaynegi45 on it 👍

**Comment by ajaynegi45** [comment]
> @ajaynegi45 did you mean that design folder?

Nope. I mean overall look

**Comment by Sourabh782** [comment]
@ajaynegi45  the issue still available?

**Comment by ajaynegi45** [comment]
> @ajaynegi45 the issue still available?
> 
> was pr made by someone else?? regarding same issue?

No pr was made. But we don't want to change it. Because this problem is with just font only.
