### ISSUE TITLE
[BUG] Update the new Twitter logo (X)

### ISSUE THREAD

**Issue by vedhcet-07** [ajaynegi45/Uttarakhand-Culture-NewUI#73]
### Is this a new issue?

- [X] I have searched "open" and "closed" issues, and this is not a duplicate.

### Bug Description

The readme file has old twitter logo . better if its updated . Small but matters

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/693c61dc-1de3-4701-9c5c-80b3195ad54a)

### Screenshots

![image](https://github.com/user-attachments/assets/d1ffd4f2-cf6f-43a7-9500-3a3739014fc0)

### Would you like to work on this issue?

Yes

### Implementation Plan

I would just change the logo . thats it . please assign this to me under hacktoberfest and gssoc .

**Comment by ajaynegi45** [comment]
> ### Is this a new issue?
> * [x]  I have searched "open" and "closed" issues, and this is not a duplicate.
> 
> ### Bug Description
> The readme file has old twitter logo . better if its updated . Small but matters
> 
> ### Steps to Reproduce
> ![image](https://private-user-images.githubusercontent.com/176995332/373775395-693c61dc-1de3-4701-9c5c-80b3195ad54a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzA2NzQsIm5iZiI6MTcyODA3MDM3NCwicGF0aCI6Ii8xNzY5OTUzMzIvMzczNzc1Mzk1LTY5M2M2MWRjLTFkZTMtNDcwMS05YzVjLTgwYjMxOTVhZDU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxOTMyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjEzMmE3NDAwZjc2OTRkOTMxOTc5ZDI5MDg5MzYyOGFmYzY1OTMyYzUwMWVlZjBkMTk0ODhiODczNjZmZjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GUN2Ym-nRYtQh60tX4RwMtSzLilZE3SQCw8o4zM7sCg)
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/176995332/373775830-d1ffd4f2-cf6f-43a7-9500-3a3739014fc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzA2NzQsIm5iZiI6MTcyODA3MDM3NCwicGF0aCI6Ii8xNzY5OTUzMzIvMzczNzc1ODMwLWQxZmZkNGYyLWNmNmYtNDNhNy05NTAwLTNhMzczOTAxNGZjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxOTMyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjI2OWRlODk0YTkwMjEwMmVhYTJkOTNlOGJjZTk4ZjRiOTZiOWQ2YzQ3MjgwY2MyOTkzNzM0YTg2OTQ2YWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.guYJmxKmtQ3PP3m_0gmTLpzgo4Rp_C2bHO7jlNl8se8)
> 
> ### Would you like to work on this issue?
> Yes
> 
> ### Implementation Plan
> I would just change the logo . thats it . please assign this to me under hacktoberfest and gssoc .

Hi @vedhcet-07,  

Thank you for your enthusiasm and interest in contributing to the project! I'm happy to let you know that the issue has been assigned to you. I appreciate that you've taken the time to review the documentation—it shows great attention to detail.

Feel free to dive in, and don't hesitate to reach out if you have any questions or need assistance along the way. We're here to help!
