### ISSUE TITLE
Dark mode toggle button 

### ISSUE THREAD

**Issue by abhishekpanthee** [ajaynegi45/Uttarakhand-Culture-NewUI#74]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

The dark mode are often user friendly to use and provides a better interface 
Another thing is the ui is pretty unappealing even for light mode with less contrast text and such

### Feature Description

there is not much of a description I am simply want to work on that as every website is equipped with this .

### Would you like to work on this feature?

Yes

**Comment by Prabal-verma** [comment]
@ajaynegi45 check this
