### ISSUE TITLE
[FEATURE] [COMMUNITY] Creating a DISCORD community around the platform (USERS + DEVS)

### ISSUE THREAD

**Issue by ShivamPande18** [ajaynegi45/Uttarakhand-Culture-NewUI#78]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

There is no way for the users to interact with each other and developers to discuss with each other. Basically the main idea is to preserve Uttarakhand culture but there is no community around it.

### Feature Description

Create a discord community where people can interact with each other. Having separate channels for user discussion and special channels for developers who want to contribute to the platform.
This way we can accomplish following things:

- Create a community around the platform and Uttarakhand culture 
- A single area where new updates and vision of the project can be shared and notified with users and devs
- Users can interact with each other
- Devs can interact with each other
- Get contribution from non tech people in terms of folk tales, cultural stories, and other stuffs
- Get feedbacks from the users
- Easier for the platform to grow

### Would you like to work on this feature?

Yes

### Implementation Plan

- Creating a discord for the platform
- Create separate user channels and verified developer channels
- Add different levels for members (eg users, devs, mods, etc)
- Add bots to make it fun and lively and to automate task like welcoming, verification, etc
- Assign moderators
- Promote the discord on the website

**Comment by ajaynegi45** [comment]
> Create a discord community where people can interact with each other.

@ShivamPande18, 
Ask for here https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/82
