### ISSUE TITLE
[FEATURE] Missing User Authentication and Login/Sign Up Route

### ISSUE THREAD

**Issue by yours7himanshu** [ajaynegi45/Uttarakhand-Culture-NewUI#79]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

1)There is no user authentication mechanism in place. Implementing JSON Web Token (JWT) authentication with MongoDB is necessary to allow secure user registration and login.

2)Sign Up Page is broken

### Feature Description

How to solve - We need to implement JSON Web Token (JWT) authentication with MongoDB

### Would you like to work on this feature?

Yes

### Implementation Plan

Setup Backend: Install necessary packages (express, bcryptjs, jsonwebtoken, mongoose, dotenv, cors).

Environment Variables: Store the JWT secret and MongoDB connection string in a .env file.

User Model: Define a MongoDB schema for users in User.js.

Express App: Set up Express, connect to MongoDB, and include user routes for registration, login, and protected routes.

JWT Logic:

Register: Hash the password and create a JWT token after saving the user.
Login: Verify user credentials, compare passwords, and return a JWT token.
Protected Route: Use JWT middleware to protect routes.
Testing: Test user registration, login, and accessing protected routes using JWT tokens.

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> 1)There is no user authentication mechanism in place. Implementing JSON Web Token (JWT) authentication with MongoDB is necessary to allow secure user registration and login.
> 
> 2)Sign Up Page is broken
> 
> ### Feature Description
> How to solve - We need to implement JSON Web Token (JWT) authentication with MongoDB
> 
> ### Screenshots
> _No response_
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> Setup Backend: Install necessary packages (express, bcryptjs, jsonwebtoken, mongoose, dotenv, cors).
> 
> Environment Variables: Store the JWT secret and MongoDB connection string in a .env file.
> 
> User Model: Define a MongoDB schema for users in User.js.
> 
> Express App: Set up Express, connect to MongoDB, and include user routes for registration, login, and protected routes.
> 
> JWT Logic:
> 
> Register: Hash the password and create a JWT token after saving the user. Login: Verify user credentials, compare passwords, and return a JWT token. Protected Route: Use JWT middleware to protect routes. Testing: Test user registration, login, and accessing protected routes using JWT tokens.

 Duplicate Issue https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/34
