### ISSUE TITLE
[FEATURE] Adding a favicon

### ISSUE THREAD

**Issue by Sourabh782** [ajaynegi45/Uttarakhand-Culture-NewUI#88]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Adding a favicon to the site. currently it's not having any favicon

### Feature Description

Adding a custom favicon like mountains (representing uttrakhand)

### Screenshots

Default:

![Screenshot 2024-10-06 080309](https://github.com/user-attachments/assets/4c755d08-bb2b-4fb0-bd50-a941b3f5860f)

For new one have to design

### Would you like to work on this feature?

Yes

### Implementation Plan

i would design a favicon featuring mountains which will represent uttrakhand

**Comment by ajaynegi45** [comment]
> i would design a favicon featuring mountains which will represent uttrakhan

Hi @Sourabh782,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Before making any contributions, please read the [Readme.md](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/README.md) file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the [Contributing.md](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/contributing.md) file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.
