### ISSUE TITLE
[FEATURE] adding icons in Footer socials

### ISSUE THREAD

**Issue by devxMani** [ajaynegi45/Uttarakhand-Culture-NewUI#96]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

add icons

### Feature Description

icons of linkedin , github, instagram

### Screenshots

![image](https://github.com/user-attachments/assets/5f9fe6c7-7964-473d-8394-0b2b3253af17)

### Would you like to work on this feature?

Yes

### Implementation Plan

make changes in footer and some transitions and logos

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> add icons
> 
> ### Feature Description
> icons of linkedin , github, instagram
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/122438942/373975168-5f9fe6c7-7964-473d-8394-0b2b3253af17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjg3NTQsIm5iZiI6MTcyODMyODQ1NCwicGF0aCI6Ii8xMjI0Mzg5NDIvMzczOTc1MTY4LTVmOWZlNmM3LTc5NjQtNDczZC04Mzk0LTBiMmIzMjUzYWYxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxOTE0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmE4ZDVmODA4YTRmNGZkNjc4ODZmMGYzZDM3NjJkNzEyM2JiODcxNzk0Y2ZhZDAxNzhmYWQ1ZThlYjRkZDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._M909-4IcyQLHgIwQKzPxJvxaMCGcZ4cSkO1k555dPo)
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> make changes in footer and some transitions and logos

Assigned

**Comment by devxMani** [comment]
@ajaynegi45 can you add labels GSOC EXT and hacktoberfest labels

**Comment by harish08102004** [comment]
Hey @ajaynegi45 if this issue is still open, I can work on this.
